apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: app
          image: rishbat12/location
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: location
  type: NodePort
---
